FROM registry.cn-beijing.aliyuncs.com/userid/debian
MAINTAINER "Gao Jie"

RUN sudo rm -rf /var/lib/apt/lists/* && sudo apt update

RUN apt-get install python3-pip vim -y
RUN apt-get install libsm6 libxrender1 libxext-dev -y
RUN echo "[global]\nindex-url = https://mirrors.aliyun.com/pypi/simple\n" > /etc/pip.conf
RUN echo "let skip_defaults_vim=1\nset mouse=\nsyntax on" >> /etc/vim/vimrc

RUN pip3 install opencv-python

RUN useradd developer -u 1001 -M -G nogroup -N
